# Generated by Django 4.0.4 on 2022-04-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.FloatField(default=0.0),
        ),
    ]
