# Generated by Django 4.0.4 on 2022-04-14 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0003_product_height_product_width'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='comments',
            field=models.TextField(blank=True),
        ),
    ]
