# Generated by Django 4.0.4 on 2022-04-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0004_product_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=256, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=256)),
                ('amount_of_works', models.IntegerField(default=0)),
            ],
        ),
    ]
