# Generated by Django 4.0.4 on 2022-04-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0006_order_productvariation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scale',
            field=models.CharField(default='Low', max_length=50),
        ),
    ]
