# Generated by Django 4.0.4 on 2022-04-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0007_order_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='end_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='end_month',
            field=models.CharField(default='January', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='send_year',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start_day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='start_month',
            field=models.CharField(default='January', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='start_year',
            field=models.IntegerField(default=0),
        ),
    ]
