# Generated by Django 4.0.4 on 2022-04-16 02:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0008_order_end_day_order_end_month_order_send_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='end_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='send_year',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_day',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='start_year',
        ),
        migrations.AddField(
            model_name='order',
            name='end_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='order',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.date.today),
        ),
    ]
