# Generated by Django 4.0.4 on 2022-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0009_remove_order_end_day_remove_order_end_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pricing',
        ),
        migrations.AddField(
            model_name='productvariation',
            name='base_price',
            field=models.IntegerField(default=0.0),
        ),
    ]
