# Generated by Django 4.0.4 on 2022-04-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0011_remove_product_height_remove_product_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariation',
            name='base_price',
            field=models.FloatField(default=0.0),
        ),
    ]
