# Generated by Django 4.0.4 on 2022-04-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digital_warehouse', '0012_alter_productvariation_base_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariation',
            old_name='base_price',
            new_name='base_pricing',
        ),
    ]
